# Generated by Django 4.2.1 on 2023-05-23 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Choose_and_Tell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_images')),
                ('contrast_setting', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preference', models.CharField(choices=[('mouse', 'Mouse'), ('button', 'Button')], max_length=10)),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
