# Generated by Django 4.2.1 on 2023-06-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choose_and_Tell', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contrast_setting',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='person',
            name='speed',
        ),
        migrations.AddField(
            model_name='person',
            name='text_clarity_setting',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
