# Generated by Django 4.2.1 on 2023-06-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choose_and_Tell', '0005_person_text_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='text_size_bool',
            field=models.BooleanField(default=False),
        ),
    ]
